#ifndef Command_H
#define Command_H

#define VEHICLE_FORWARD 		201
#define VEHICLE_BACKWARD 		211
#define VEHICLE_FORWARD_TURN_LEFT 	221
#define VEHICLE_FORWARD_TURN_RIGHT	231
#define VEHICLE_BACKWARD_TURN_LEFT 	241
#define VEHICLE_BACKWARD_TURN_RIGHT	251
#define VEHICLE_SPIN_CLOCKWISE		261
#define VEHICLE_SPIN_COUNTERCLOCKWISE	271
#define VEHICLE_STOP			281

#endif
